### ISSUE TITLE
Cannot draw loose selection when marching ants is active

### ISSUE THREAD

**Issue by merwinvandijk** [ArnoldSwaggernegger/ariana#139]
When using the loose selection tool a dotted line is drawn around the "loose selection". The first time using the loose selection tool the dotted line is draw fine however after the first loose selection is made the second selection used marching ants to draw instead of the dotted line. It seems like a switch in modus is mage because drawing of the ants seems far more laggy.

Related files (?):
loose.directive.js
edit-engine.ts
draw-eninge.ts

**Comment by sjerdo** [comment]
Fixed in commit 634313e
