### ISSUE TITLE
Creating shared variables between controllers using $scope

### ISSUE THREAD

**Issue by merwinvandijk** [ArnoldSwaggernegger/ariana#144]
If I create a variable in one controller ($scope.test = 37) it is undefined in others controllers. I think the variable is only defined within the controller where it is created. How do I create shared variables for multiple controllers?

**Comment by merwinvandijk** [comment]
I put them in app.js that seemed to work. (solved?)

**Comment by TengenJulian** [comment]
I'm unsure what you need. But communication between controllers can be done with the use
of event listeners. See:
http://stackoverflow.com/questions/9293423/can-one-controller-call-another
