### ISSUE TITLE
fix or remove drawing between layers

### ISSUE THREAD

**Issue by sjerdo** [ArnoldSwaggernegger/ariana#172]
This is broken.

**Comment by Scoudem** [comment]
Please explain @sjerdo

**Comment by sjerdo** [comment]
@Scoudem First it was possible to draw between two layers. (eg. between the second and third layer)
During a recent update to app.js, this functionality broke.
Now it only works partially: Tthe upper layers are still drawn in the top-canvas, so you'll draw under these layers, but the drawing result is added as layer on top of everything.

**Comment by sjerdo** [comment]
Related issues: #130  #132
