### ISSUE TITLE
Grid background borked when zooming

### ISSUE THREAD

**Issue by Scoudem** [ArnoldSwaggernegger/ariana#210]
Can you have a look @mathijs727 (cleanup branch)

![screenshot from 2015-06-25 15-35-05](https://cloud.githubusercontent.com/assets/6672908/8355488/d9f90fe4-1b4f-11e5-9eed-c549e1382562.png)

**Comment by Scoudem** [comment]
fixed in ea0ac78234bfde27c5f12d4853f44a649932e8c0

**Comment by sjerdo** [comment]
😹
