### ISSUE TITLE
Change color of svg images

### ISSUE THREAD

**Issue by jurrew27** [ArnoldSwaggernegger/ariana#30]

**Comment by ArnoldSwaggernegger** [comment]
Dit gaat waarschijnlijk niet lukken, waarschijnlijk moeten we pngs maken

**Comment by sjerdo** [comment]
Je kunt de broncode / DOM van de svg aanpassen en dan een kleurwaarde instellen in het fill attribuut van het path.

**Comment by Scoudem** [comment]
This is gonna be different
