### ISSUE TITLE
<link>-tags generated by Grunt are not closed by </link>-tags

### ISSUE THREAD

**Issue by ArnoldSwaggernegger** [ArnoldSwaggernegger/ariana#39]
The `<link>`-tags generated by Grunt for the css-files generated by the DEV-option are not closed by a `</link>` tag.

**Comment by TengenJulian** [comment]
Dit lijkt meer op een firefox bug of zo. Voor html5 geldt dat link geen end tag heeft.

**Comment by Scoudem** [comment]
@TengenJulian Yup, `<link>` tags do not have a closing tag as of HTML5. Closing `<link>` tags was compliant with XHTML.

**Comment by ArnoldSwaggernegger** [comment]
Dit is inderdaad HTML5. Firefox moetn niet zo bitchen
