### ISSUE TITLE
bergen "not well-formed" warnings in demo branch

### ISSUE THREAD

**Issue by ArnoldSwaggernegger** [ArnoldSwaggernegger/ariana#40]
De huidige gui-prototype en demo branches genereren heel veel "not well-formed" warnings. Ik dacht eerste dat ze van de JSON definities kwamen, maar die zijn nu gefixt (inclusief strings als keys).

**Comment by ArnoldSwaggernegger** [comment]
Deze warnings hebben te maken met het laden van de SVG's. Die leveren deze error op.

**Comment by TengenJulian** [comment]
Angular vraagt de svg met XHR op maar doet iets vaags wat Firefox niet leuk vindt.
Vervangen van src met ng-src lijkt het op te lossen.
