### ISSUE TITLE
Bucket fill

### ISSUE THREAD

**Issue by mathijs727** [ArnoldSwaggernegger/ariana#67]
Nadat selectie gedaan is

**Comment by merwinvandijk** [comment]
Het daadwerkelijk vullen van een selectie is gegeven de bitmask niet veel werk. Ik denk dat dit in de renderengine moet gebeuren?

**Comment by merwinvandijk** [comment]
Algoritmes gegeven een target color, replacement color en een starting node staan in pseudo code hier beschreven:

https://en.wikipedia.org/wiki/Flood_fill
